package generatedbyassl.as.aes.goldlevelsubscriber.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'MonitorQoSGold' (specified as ACTION ASSL tier).
 */
public class MONITORQOSGOLD
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'MONITORQOSGOLD' class.
	 */
	static private MONITORQOSGOLD oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  MONITORQOSGOLD (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'MONITORQOSGOLD' class.
	 */
	static public MONITORQOSGOLD getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new MONITORQOSGOLD();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Provides conditions to be fulfilled before processing the action.
	 */
	public boolean GUARDS (  )
	{
		boolean bResult = true;
		bResult =  generatedbyassl.as.aes.goldlevelsubscriber.aeself_management.qosgold.INMONITORINGQOSGOLD.getInstance().isFluentInitiated()  ;
		return bResult;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the action if the GURADS conditions are fulfilled.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.aes.goldlevelsubscriber.aeip.managed_elements.GOLDQOSMONITORING.getInstance().REPORTBANDWIDTH(  );
		generatedbyassl.as.aes.goldlevelsubscriber.aeip.managed_elements.GOLDQOSMONITORING.getInstance().REPORTQOSPERFORMANCE(  );
	}

}