package generatedbyassl.as.autonomicnetwork;

import java.io.Serializable;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'DataACL' (specified as an ASSL custom type).
 */
public class DATAACL
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * ASSL generates an empty classes for each custom-defined type. Complete this class to implement all needed functionality.
	 */

	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

}