package generatedbyassl.as.aes.controller.aeself_management;

import java.io.Serializable;
import generatedbyassl.as.ASSLPOLICY;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'SELF_CONFIGURING' (specified as SELF_CONFIGURING ASSL tier).
 */
public class SELF_CONFIGURING
	extends ASSLPOLICY
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'SELF_CONFIGURING' class.
	 */
	static private SELF_CONFIGURING oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  SELF_CONFIGURING (  )
	{
		vFluents.put( "INIDENTIFYTRAFFICTYPE", generatedbyassl.as.aes.controller.aeself_management.self_configuring.INIDENTIFYTRAFFICTYPE.getInstance() );
		vFluents.put( "INCLASSIFICATION", generatedbyassl.as.aes.controller.aeself_management.self_configuring.INCLASSIFICATION.getInstance() );
		vFluents.put( "INLABELINGQOS", generatedbyassl.as.aes.controller.aeself_management.self_configuring.INLABELINGQOS.getInstance() );
		vFluents.put( "INPOLICING", generatedbyassl.as.aes.controller.aeself_management.self_configuring.INPOLICING.getInstance() );
		vFluents.put( "INMARKING", generatedbyassl.as.aes.controller.aeself_management.self_configuring.INMARKING.getInstance() );
		vFluents.put( "INEVALUATION", generatedbyassl.as.aes.controller.aeself_management.self_configuring.INEVALUATION.getInstance() );
		vFluents.put( "INQOSGOLDSETTING", generatedbyassl.as.aes.controller.aeself_management.self_configuring.INQOSGOLDSETTING.getInstance() );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'SELF_CONFIGURING' class.
	 */
	static public SELF_CONFIGURING getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new SELF_CONFIGURING();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * For each specified MAPPING, checks if the MAPPING conditions are fulfilled and if so spawn a thread to perform the MAPPING actions.
	 */
	public synchronized void doAllMappings (  )
	{
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.controller.aeself_management.self_configuring.INIDENTIFYTRAFFICTYPE.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.controller.actions.IDENTIFYTRAFFIC.getInstance().perform(  );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INIDENTIFYTRAFFICTYPE" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INIDENTIFYTRAFFICTYPE");
				runActions.start();
			}
		}
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.controller.aeself_management.self_configuring.INCLASSIFICATION.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.controller.actions.CLASSIFYPACKETS.getInstance().perform(  );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INCLASSIFICATION" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INCLASSIFICATION");
				runActions.start();
			}
		}
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.controller.aeself_management.self_configuring.INLABELINGQOS.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.controller.actions.LABELTRAFFIC.getInstance().perform(  );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INLABELINGQOS" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INLABELINGQOS");
				runActions.start();
			}
		}
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.controller.aeself_management.self_configuring.INPOLICING.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.controller.actions.POLICING.getInstance().perform(  );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INPOLICING" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INPOLICING");
				runActions.start();
			}
		}
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.controller.aeself_management.self_configuring.INMARKING.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.controller.actions.MARKTRAFFIC.getInstance().perform(  );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INMARKING" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INMARKING");
				runActions.start();
			}
		}
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.controller.aeself_management.self_configuring.INEVALUATION.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.controller.actions.EVALUATEQOS.getInstance().perform(  );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INEVALUATION" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INEVALUATION");
				runActions.start();
			}
		}
		//************************ MAPPING ***********************
		if ( generatedbyassl.as.aes.controller.aeself_management.self_configuring.INQOSGOLDSETTING.getInstance().isFluentInitiated() ) 
		{
			//**** runs a thread that performs the actions mapped to these fluents
			Runnable actionsRunner = new Runnable()
			{
				/**
				 * Generated by ASSL Framework
				 * 
				 * This method runs the mapping thread until all the mapped actions have been performed.
				 */
				public void run (  )
				{
					try
					{
						generatedbyassl.as.aes.controller.actions.SETQOSGOLD.getInstance().perform(  );
					}
					catch ( Exception ex ) 
					{
						System.err.println( ex.getMessage() );
					}
				}

			};
			//**** creates and starts the thread if the latter is not currently running
			if ( !isMappingRunning( "INQOSGOLDSETTING" ) ) 
			{
				Thread runActions = new Thread(thrdgrMappings, actionsRunner, "INQOSGOLDSETTING");
				runActions.start();
			}
		}
	}

}