package generatedbyassl.as.aes.goldlevelsubscriber.aeip.functions;

import java.io.Serializable;
import generatedbyassl.as.ASSLFUNCTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'receiveMsgQoSGold' (specified as FUNCTION ASSL tier).
 */
public class RECEIVEMSGQOSGOLD
	extends ASSLFUNCTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'RECEIVEMSGQOSGOLD' class.
	 */
	static private RECEIVEMSGQOSGOLD oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  RECEIVEMSGQOSGOLD (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'RECEIVEMSGQOSGOLD' class.
	 */
	static public RECEIVEMSGQOSGOLD getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new RECEIVEMSGQOSGOLD();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Embeds statements to be performed by the function.
	 */
	public void DOES (  )
	{
		super.DOES();
		generatedbyassl.as.aes.controller.aeip.channels.GOLDLINK.getInstance().getMessage("generatedbyassl.as.aes.controller.aeip.messages.MSGQOSGOLD");
	}

}