package generatedbyassl.as.aes.controller.actions;

import java.io.Serializable;
import generatedbyassl.as.ASSLACTION;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'InputAndOutput' (specified as ACTION ASSL tier).
 */
public class INPUTANDOUTPUT
	extends ASSLACTION
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INPUTANDOUTPUT' class.
	 */
	static private INPUTANDOUTPUT oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INPUTANDOUTPUT (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INPUTANDOUTPUT' class.
	 */
	static public INPUTANDOUTPUT getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INPUTANDOUTPUT();
		}
		return oInstance;
	}

}