package generatedbyassl.as.aes;

import java.io.Serializable;
import generatedbyassl.as.ASSLAE;
import generatedbyassl.as.aes.goldlevelsubscriber.controlloop.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'GoldLevelSubscriber' (specified as AE ASSL tier).
 */
public class GOLDLEVELSUBSCRIBER
	extends ASSLAE
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'GOLDLEVELSUBSCRIBER' class.
	 */
	static private GOLDLEVELSUBSCRIBER oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's monitor.
	 */
	private GOLDLEVELSUBSCRIBER_ASSLMONITOR oMonitor = new GOLDLEVELSUBSCRIBER_ASSLMONITOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's analyzer.
	 */
	private GOLDLEVELSUBSCRIBER_ASSLANALYZER oAnalyzer = new GOLDLEVELSUBSCRIBER_ASSLANALYZER();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's simulator.
	 */
	private GOLDLEVELSUBSCRIBER_ASSLSIMULATOR oSimulator = new GOLDLEVELSUBSCRIBER_ASSLSIMULATOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's executor.
	 */
	private GOLDLEVELSUBSCRIBER_ASSLEXECUTOR oExecutor = new GOLDLEVELSUBSCRIBER_ASSLEXECUTOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AEIP class.
	 */
	public generatedbyassl.as.aes.goldlevelsubscriber.AEIP AEIP = generatedbyassl.as.aes.goldlevelsubscriber.AEIP.getInstance();

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  GOLDLEVELSUBSCRIBER (  )
	{
		vPolicies.put( "QOSGOLD", generatedbyassl.as.aes.goldlevelsubscriber.aeself_management.QOSGOLD.getInstance() );
		ACTIONS.put( "QOSGOLD", generatedbyassl.as.aes.goldlevelsubscriber.actions.QOSGOLD.getInstance() );
		ACTIONS.put( "MONITORQOSGOLD", generatedbyassl.as.aes.goldlevelsubscriber.actions.MONITORQOSGOLD.getInstance() );
		EVENTS.put( "TIMETOINITIATEQOS", generatedbyassl.as.aes.goldlevelsubscriber.events.TIMETOINITIATEQOS.getInstance() );
		EVENTS.put( "QOSINITIATED", generatedbyassl.as.aes.goldlevelsubscriber.events.QOSINITIATED.getInstance() );
		EVENTS.put( "QOSGOLDMONITORED", generatedbyassl.as.aes.goldlevelsubscriber.events.QOSGOLDMONITORED.getInstance() );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'GOLDLEVELSUBSCRIBER' class.
	 */
	static public GOLDLEVELSUBSCRIBER getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new GOLDLEVELSUBSCRIBER();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Sets the control loop components.
	 */
	protected void setControlLoop (  )
	{
		//**** This method overrides the super class's method.
		//****************************************************
		oMonitor.setMonitoredSLO(AESLO);
		oMonitor.setMonitoredMetrics(METRICS);
		oMonitor.setAnalyzer(oAnalyzer);
		oAnalyzer.setSimulator(oSimulator);
		oAnalyzer.setExecutor(oExecutor);
		oSimulator.setExecutor(oExecutor);
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the AE control loop.
	 */
	protected void controlLoop (  )
	{
		//**** This method overrides the super class's method.
		//****************************************************
		try
		{
			//**** control loops should not be very resource-consuming, thus it releases CPU for a while
			Thread.sleep(1000);
		}
		catch ( InterruptedException ex ) 
		{
			System.err.println( ex.getMessage() );
		}
		//**** performs AE control loop monitor-analyzer-simulator-executor
		oMonitor.perform();
		oAnalyzer.perform();
		oSimulator.perform();
		oExecutor.perform();
		//**** applies all the "switched-on" self-management policies for the AS
		applayPolicies();
	}

}