package generatedbyassl.as.aes.controller.metrics;

import java.io.Serializable;
import generatedbyassl.as.ASSLMETRIC;
import java.lang.Integer;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'CoS' (specified as METRIC ASSL tier).
 */
public class COS
	extends ASSLMETRIC
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'COS' class.
	 */
	static private COS oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * The metric's value - ASSL VALUE {} clause.
	 */
	public Integer VALUE = new Integer(0);
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds the old VALUE of the metric.
	 */
	protected Integer oldVALUE = new Integer(0);

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  COS (  )
	{
		METRIC_TYPE = "RESOURCE";
		DESCRIPTION = "class of service field";
		MEASURE_UNIT = "";
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'COS' class.
	 */
	static public COS getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new COS();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Checks whether the metric is valid. A metric is considered valid (true) iff the value it is holding satisfies all the threshold class values.
	 */
	public synchronized boolean isValid (  )
	{
		boolean bValid = false;
		int iEqlLeft = VALUE.compareTo(  new Integer( new Float(0).intValue() ) );
		int iEqlRght = VALUE.compareTo(  new Integer( new Float(7).intValue() ) );
		if ( (iEqlLeft >= 0) &&
			 (iEqlRght <= 0) ) 
		{
			bValid = true;
		}
		else
		{
			bValid = false;
		}
		return bValid;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Updates the metric value.
	 */
	public synchronized void refresh (  )
	{
		//**** checks if the metric has changed its VALUE since the last refresh
		int iEql = VALUE.compareTo( oldVALUE );
		if ( iEql == 0 ) 
		{
			bHasChanged = false;
		}
		else
		{
			oldVALUE = new Integer( VALUE.intValue() );
			bHasChanged = true;
		}
	}

}