package generatedbyassl.as.aes.goldlevelsubscriber.aeip.managed_elements;

import java.io.Serializable;
import generatedbyassl.as.ASSLMANAGED_ELEMENT;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'GoldQoSMonitoring' (specified as MANAGED_ELEMENT ASSL tier).
 */
public class GOLDQOSMONITORING
	extends ASSLMANAGED_ELEMENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'GOLDQOSMONITORING' class.
	 */
	static private GOLDQOSMONITORING oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  GOLDQOSMONITORING (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'GOLDQOSMONITORING' class.
	 */
	static public GOLDQOSMONITORING getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new GOLDQOSMONITORING();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Management element interface function.
	 */
	public void REPORTBANDWIDTH (  )
	{
		//**** Implement this method.
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Management element interface function.
	 */
	public void REPORTQOSPERFORMANCE (  )
	{
		//**** Implement this method.
	}

}