package generatedbyassl.as.aes.controller.aeself_management.self_configuring;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'InPolicing' (specified as FLUENT ASSL tier).
 */
public class INPOLICING
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INPOLICING' class.
	 */
	static private INPOLICING oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INPOLICING (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.controller.events.TIMETOPOLICING.getInstance() );
		generatedbyassl.as.aes.controller.events.TIMETOPOLICING.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.controller.events.POLICINGDONE.getInstance() );
		generatedbyassl.as.aes.controller.events.POLICINGDONE.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INPOLICING' class.
	 */
	static public INPOLICING getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INPOLICING();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}